### ISSUE TITLE
Decide on a guiding backend framework/solution

### ISSUE THREAD

**Issue by Nyumat** [OSU-App-Club/party-finder#3]
This decision depends on the outcome of issue #2 (native vs. cross-platform). 

But or now, we need to evaluate backend options that align with our development strategy. Ideally, we should consider performance, scalability, ease of integration with the frontend, and long-term maintenance. Potential solutions include:

- Node.js (Express, NestJS)
- Django (Python)
- Firebase (Serverless)
- Supabase
- & More!

**Comment by owenkrause** [comment]
We decided on Express.js since most people were familiar with it.
